# site settings
title: SAMRAWIT FELEKE 
subtitle: DATA SCIENTIST. CONSULTANT
email: hello@samrawit-page
description: I MAKE THINGS HAPPEN.
# <br /> and released under the Creative Commons.



baseurl: "/samrawit-page" # the subpath of your site, e.g. /blog
url: https://www.samrawit-page # the base hostname & protocol for your site
author: Samrawit Feleke
street_address: 1234 Somewhere Road
city: Washington
state: DC
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://stech2020.github.io
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/samrawitf
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown
remote_theme: Forty 
sass:
  style: compressed
